version: '3.9'
name: youtogether

networks:
  proxy:
    name: "proxy"

services:
  traefik:
    container_name: proxy
    hostname: traefik
    image: traefik:v2.10
    labels:
      traefik.enable: "true"
      traefik.http.routers.traefik.entrypoints: "websecure"
      traefik.http.routers.traefik.rule: "Host(`traefik.${DOMAIN_NAME}`)"
      traefik.http.routers.traefik.tls: "true"
      traefik.http.routers.traefik.service: "api@internal"
      traefik.http.middlewares.corsheader.headers.accesscontrolalloworiginlist: https://localhost
    restart: unless-stopped
    expose:
      - "8080"
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./services/traefik/dynamic-config.yaml:/etc/traefik/dynamic-config.yaml:ro
      - ./services/traefik/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./tls:/etc/tls
    networks:
      - proxy

  postgres:
    container_name: postgres
    image: postgres:15-alpine3.17
    restart: unless-stopped
    networks:
      - proxy
    labels:
      traefik.enable: "false"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USERNAME}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    container_name: redis
    image: redis:7.0.9-alpine3.17
    restart: unless-stopped
    networks:
      - proxy
    labels:
      traefik.enable: "false"
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 8s
      timeout: 5s
      retries: 5

  frontend:
    container_name: frontend
    image: ghcr.io/youtogether-online/frontend:main
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.frontend.rule: "Host(`${DOMAIN_NAME}`)"
      traefik.http.routers.frontend.tls: "true"
      traefik.http.routers.frontend.entrypoints: "websecure"
    expose:
      - "5173"
    networks:
      - proxy
    environment:
      API_URL: https://youtogether.local/api
      PORT: "5173"

  backend:
    container_name: backend
    image: ghcr.io/youtogether-online/backend:main
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    labels:
      traefik.enable: "true"
      traefik.http.routers.backend.rule: "Host(`${DOMAIN_NAME}`) && PathPrefix(`/api`)"
      traefik.http.services.backend.loadbalancer.server.port: "3000"
      traefik.http.routers.backend.tls: "true"
      traefik.http.routers.backend.entrypoints: "websecure"
    expose:
      - "3000"
    networks:
      - proxy
    environment:
        COOKIE_NAME: session_id
        COOKIE_PATH: /api
        COOKIE_DURATION: 720h
        POSTGRES_USERNAME: ${POSTGRES_USERNAME}
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        HOST: localhost
        PORT: 3000
        EMAIL_FROM: ${EMAIL_FROM}
        EMAIL_USER: ${EMAIL_USER}
        EMAIL_PASSWORD: ${EMAIL_PASSWORD}
#        EMAIL_STMP_HOST: ${EMAIL_STMP_HOST}
#        EMAIL_PORT: ${EMAIL_PORT}
