http:
  middlewares:
    security-headers:
      headers:
        frameDeny: true
        sslRedirect: true
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        forceSTSHeader: true
        contentTypeNosniff: true
        isDevelopment: false
        accessControlAllowMethods: "*"
        accessControlAllowHeaders: "*"
        accessControlAllowOriginList:
          - https://localhost:5173
        accessControlMaxAge: 100
        addVaryHeader: true

tls:
  certificates:
    - certFile: "/tls/youtogether-local-cert.pem"
      keyFile: "/tls/youtogether-local-key.pem"