http:
  middlewares:
    dashboard-auth:
      basic-auth:
        users:
          - "admin:$2y$19$XTlzI4VCrofnL87xC/5zKehkGTDkRSksOywgkFOBXHAZHTIdO9PZ6"
    security-headers:
      headers:
        frameDeny: true
        sslRedirect: true
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        forceSTSHeader: true
        contentTypeNosniff: true
        isDevelopment: false
        accessControlMaxAge: 100
        addVaryHeader: true