http:
  middlewares:
    api-stripprefix:
      stripPrefix:
        prefixes:
          - "/api/internal"

tls:
  certificates:
    - certFile: "/etc/tls/youtogether-local-cert.pem"
      keyFile: "/etc/tls/youtogether-local-key.pem"