global:
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true

log:
  level: ERROR

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    exposedByDefault: false
    network: "youtogether_proxy"

  file:
    filename: "/etc/traefik/config.yaml"
    watch: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "websecure"
          scheme: "https"
          permanent: true
  websecure:
    address: ":443"
    http:
      middlewares:
        - security-headers@file

certificatesResolvers:
  le:
    acme:
      email: frkam@icloud.com
      storage: /tls/acme.json
      httpChallenge:
        entryPoint: web