name: Deploy Dev

on:
  push:
    branches: main
    paths:
      - "docker-compose.yaml"
      - "dev.yaml"
      - ".github/workflows/dev-deploy.yml"
      - "services/*"
  repository_dispatch:
    types:
      - deploy-dev
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      POSTGRES_USERNAME: ${{ secrets.DEV_POSTGRES_USERNAME }}
      POSTGRES_DB: ${{ secrets.DEV_POSTGRES_DB }}
      POSTGRES_PASSWORD: ${{ secrets.DEV_POSTGRES_PASSWORD }}
      POSTGRES_HOST: ${{ secrets.DEV_POSTGRES_HOST }}
      DOMAIN_NAME: ${{ secrets.DEV_DOMAIN_NAME }}
      EMAIL: ${{ secrets.DEV_EMAIL }}
      EMAIL_FROM: "youtogether"
      EMAIL_USER: ""
      EMAIL_PASSWORD: ""
      EMAIL_STMP_HOST: ""
      EMAIL_PORT: ""
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create env file from secrets
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_POSTGRES_USERNAME: ${{ secrets.DEV_POSTGRES_USERNAME }}
          envkey_POSTGRES_DB: ${{ secrets.DEV_POSTGRES_DB }}
          envkey_POSTGRES_PASSWORD: ${{ secrets.DEV_POSTGRES_PASSWORD }}
          envkey_POSTGRES_HOST: ${{ secrets.DEV_POSTGRES_HOST }}
          envkey_DOMAIN_NAME: ${{ secrets.DEV_DOMAIN_NAME }}
          envkey_EMAIL: ${{ secrets.DEV_EMAIL }}
          file_name: .env
      - name: Copy repository contents via scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USERNAME }}
          password: ${{ secrets.DEV_PASSWORD }}
          source: "."
          target: "/root/releases"
      - name: Run docker-compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USERNAME }}
          password: ${{ secrets.DEV_PASSWORD }}
          script: |
            docker compose -f ./docker-compose.yaml -f ./docker-compose.dev.yaml pull --quiet
            docker compose -f ./docker-compose.yaml -f ./docker-compose.dev.yaml build
            docker compose -f ./docker-compose.yaml -f ./docker-compose.dev.yaml up -d --remove-orphans
