name: Deploy Dev

on:
  push:
    branches: main
    paths:
      - "docker-compose.yaml"
      - "dev.yaml"
      - ".github/workflows/dev-deploy.yaml"
      - "services/*"
  repository_dispatch:
    types:
      - deploy-dev
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, dev]
    defaults:
      run:
        working-directory: /root/releases
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create env file
        uses: SpicyPizza/create-envfile@v1.3.0
        with:
          envkey_POSTGRES_USERNAME: ${{ secrets.DEV_POSTGRES_USERNAME }}
          envkey_POSTGRES_DB: ${{ secrets.DEV_POSTGRES_DB }}
          envkey_POSTGRES_PASSWORD: ${{ secrets.DEV_POSTGRES_PASSWORD }}
          envkey_POSTGRES_HOST: ${{ secrets.DEV_POSTGRES_HOST }}
          envkey_DOMAIN_NAME: ${{ secrets.DEV_DOMAIN_NAME }}
          envkey_EMAIL: ${{ secrets.DEV_EMAIL }}
      - name: Update repository
        run: |
          git clean -f
          git fetch -p
      - name: Run docker compose
        run: |
          docker-compose -f docker-compose.yaml -f docker-compose.dev.yaml pull --quiet
          docker-compose -f docker-compose.yaml -f docker-compose.dev.yaml build
          docker-compose -f docker-compose.yaml -f docker-compose.dev.yaml up -d --remove-orphans
      - name: Clean docker containers and volumes
        run: docker system prune -a --volumes -f
