name: Deploy Dev

on:
  push:
    branches: main
    paths:
      - "docker-compose.yaml"
      - "dev.yaml"
      - ".github/workflows/dev-deploy.yaml"
      - "services/*"
  repository_dispatch:
    types:
      - deploy-dev
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, dev]
    defaults:
      run:
        working-directory: /root/releases
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Log
        run: |
          ls
